import type { BodyDefinition } from './types';

export interface SimulationPreset {
  readonly id: string;
  readonly name: string;
  readonly summary: string;
  readonly bodies: readonly BodyDefinition[];
  readonly fixedStep: number;
  readonly timeScale: number;
  readonly cameraDistance: number;
  readonly trailSpan: number;
}

const body = (definition: BodyDefinition): BodyDefinition => definition;

const barycentricBodies = (definitions: readonly BodyDefinition[]): BodyDefinition[] => {
  const totalMass = definitions.reduce((sum, definition) => sum + definition.mass, 0);
  const center = [0, 0, 0];
  const centerVelocity = [0, 0, 0];

  for (const definition of definitions) {
    for (let component = 0; component < 3; component += 1) {
      center[component] =
        center[component]! + definition.position[component]! * definition.mass;
      centerVelocity[component] =
        centerVelocity[component]! + definition.velocity[component]! * definition.mass;
    }
  }

  return definitions.map((definition) => ({
    ...definition,
    position: [
      definition.position[0] - center[0]! / totalMass,
      definition.position[1] - center[1]! / totalMass,
      definition.position[2] - center[2]! / totalMass,
    ],
    velocity: [
      definition.velocity[0] - centerVelocity[0]! / totalMass,
      definition.velocity[1] - centerVelocity[1]! / totalMass,
      definition.velocity[2] - centerVelocity[2]! / totalMass,
    ],
  }));
};

export const presets = [
  {
    id: 'solar-system',
    name: 'Idealized solar system',
    summary: 'JPL-derived mass ratios and orbital scales in a circular, coplanar model.',
    fixedStep: 0.0025,
    timeScale: 0.42,
    cameraDistance: 42,
    trailSpan: 72,
    bodies: [
      body({
        id: 'sun',
        name: 'Sun',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.00465047,
        renderRadius: 0.34,
        color: '#ffd685',
        axialTilt: 0.1265,
        rotationRate: 14.18,
        position: [-0.010085310860747045, 0, 0],
        velocity: [0, -0.000536927021530575, 0],
      }),
      body({
        id: 'mercury',
        name: 'Mercury',
        kind: 'rocky',
        surface: 'mercury',
        mass: 1.66012082546e-7,
        radius: 0.000016306,
        renderRadius: 0.052,
        color: '#b9aca0',
        axialTilt: 0.00059,
        rotationRate: 6.228,
        position: [0.38709927, 0, 0],
        velocity: [0, 1.6072699454, 0],
      }),
      body({
        id: 'venus',
        name: 'Venus',
        kind: 'terrestrial',
        surface: 'venus',
        mass: 2.4478382878e-6,
        radius: 0.000040454,
        renderRadius: 0.071,
        color: '#e7b675',
        axialTilt: 3.095,
        rotationRate: -1.503,
        position: [0.72333566, 0, 0],
        velocity: [0, 1.17579081149, 0],
      }),
      body({
        id: 'earth',
        name: 'Earth',
        kind: 'terrestrial',
        surface: 'earth',
        mass: 3.00348961546e-6,
        radius: 0.000042587,
        renderRadius: 0.078,
        color: '#6ca9ff',
        axialTilt: 0.4091,
        rotationRate: 366.24,
        position: [1.00000261, 0, 0],
        velocity: [0, 0.999998695003, 0],
      }),
      body({
        id: 'mars',
        name: 'Mars',
        kind: 'rocky',
        surface: 'mars',
        mass: 3.22715608293e-7,
        radius: 0.000022657,
        renderRadius: 0.061,
        color: '#df7557',
        axialTilt: 0.4396,
        rotationRate: 356.0,
        position: [1.52371034, 0, 0],
        velocity: [0, 0.810118952798, 0],
      }),
      body({
        id: 'jupiter',
        name: 'Jupiter',
        kind: 'gas-giant',
        surface: 'jupiter',
        mass: 9.54791909941e-4,
        radius: 0.00046733,
        renderRadius: 0.18,
        color: '#deb488',
        axialTilt: 0.0546,
        rotationRate: 883.2,
        position: [5.202887, 0, 0],
        velocity: [0, 0.438407326353, 0],
      }),
      body({
        id: 'saturn',
        name: 'Saturn',
        kind: 'gas-giant',
        surface: 'saturn',
        mass: 2.85885670025e-4,
        radius: 0.00038926,
        renderRadius: 0.16,
        color: '#e8d09b',
        axialTilt: 0.4665,
        rotationRate: 822.6,
        position: [9.53667594, 0, 0],
        velocity: [0, 0.323818373694, 0],
      }),
      body({
        id: 'uranus',
        name: 'Uranus',
        kind: 'ice-giant',
        surface: 'uranus',
        mass: 4.365e-5,
        radius: 0.00016953,
        renderRadius: 0.12,
        color: '#a8e2e8',
        axialTilt: 1.706,
        rotationRate: -508.7,
        position: [19.18916464, 0, 0],
        velocity: [0, 0.228282843203, 0],
      }),
      body({
        id: 'neptune',
        name: 'Neptune',
        kind: 'ice-giant',
        surface: 'neptune',
        mass: 5.149e-5,
        radius: 0.00016459,
        renderRadius: 0.12,
        color: '#477ceb',
        axialTilt: 0.4943,
        rotationRate: 543.9,
        position: [30.06992276, 0, 0],
        velocity: [0, 0.182361783677, 0],
      }),
    ],
  },
  {
    id: 'black-hole-flyby',
    name: 'Black hole flyby',
    summary: 'A compact object crosses a young planetary system and exchanges energy with every body.',
    fixedStep: 0.001,
    timeScale: 0.52,
    cameraDistance: 8.5,
    trailSpan: 16,
    bodies: barycentricBodies([
      body({
        id: 'flyby-star',
        name: 'Host star',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.075,
        renderRadius: 0.22,
        color: '#ffd284',
        axialTilt: 0.12,
        rotationRate: 2.4,
        position: [0, 0, 0],
        velocity: [0, 0, 0],
      }),
      body({
        id: 'inner-world',
        name: 'Inner world',
        kind: 'terrestrial',
        surface: 'earth',
        mass: 0.002,
        radius: 0.025,
        renderRadius: 0.082,
        color: '#68a8ee',
        axialTilt: 0.31,
        rotationRate: 4.2,
        position: [0.9, 0, 0],
        velocity: [0, 1.054, 0],
      }),
      body({
        id: 'outer-giant',
        name: 'Outer giant',
        kind: 'gas-giant',
        surface: 'jupiter',
        mass: 0.015,
        radius: 0.055,
        renderRadius: 0.14,
        color: '#d9af82',
        axialTilt: 0.08,
        rotationRate: 5.8,
        position: [1.8, 0, 0],
        velocity: [0, 0.745, 0],
      }),
      body({
        id: 'intruder-black-hole',
        name: 'Intruder black hole',
        kind: 'black-hole',
        surface: 'none',
        mass: 2,
        radius: 0.04,
        renderRadius: 0.17,
        color: '#ff9d52',
        axialTilt: 0.34,
        rotationRate: 1.2,
        position: [-5.2, -1.25, 0],
        velocity: [0.74, 0.11, 0],
      }),
    ]),
  },
  {
    id: 'black-hole-binary',
    name: 'Black hole and star',
    summary: 'A star and a black hole orbit their barycentre while two worlds respond to the combined field.',
    fixedStep: 0.001,
    timeScale: 0.48,
    cameraDistance: 10,
    trailSpan: 20,
    bodies: barycentricBodies([
      body({
        id: 'binary-black-hole',
        name: 'Black hole',
        kind: 'black-hole',
        surface: 'none',
        mass: 4,
        radius: 0.055,
        renderRadius: 0.19,
        color: '#ffac67',
        axialTilt: 0.24,
        rotationRate: 1.4,
        position: [-0.5, 0, 0],
        velocity: [0, -0.2828427125, 0],
      }),
      body({
        id: 'binary-star-companion',
        name: 'Companion star',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.085,
        renderRadius: 0.23,
        color: '#a8caff',
        axialTilt: 0.08,
        rotationRate: 2.1,
        position: [2, 0, 0],
        velocity: [0, 1.13137085, 0],
      }),
      body({
        id: 'circumbinary-world',
        name: 'Circumbinary world',
        kind: 'terrestrial',
        surface: 'earth',
        mass: 0.001,
        radius: 0.022,
        renderRadius: 0.085,
        color: '#5ea4f0',
        axialTilt: 0.42,
        rotationRate: 4.6,
        position: [0, 5.2, 0],
        velocity: [-0.981, 0, 0],
      }),
      body({
        id: 'outer-ice-world',
        name: 'Outer ice world',
        kind: 'ice-giant',
        surface: 'neptune',
        mass: 0.004,
        radius: 0.038,
        renderRadius: 0.11,
        color: '#477ceb',
        axialTilt: 0.5,
        rotationRate: 3.8,
        position: [0, -7.2, 0],
        velocity: [0.834, 0, 0],
      }),
    ]),
  },
  {
    id: 'binary-stars',
    name: 'Binary stars',
    summary: 'Two equal stars orbit their shared center of mass.',
    fixedStep: 0.0025,
    timeScale: 0.7,
    cameraDistance: 5.5,
    trailSpan: 12,
    bodies: [
      body({
        id: 'amber-star',
        name: 'Amber star',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.16,
        renderRadius: 0.16,
        color: '#ffc66d',
        position: [-1, 0, 0],
        velocity: [0, -0.5, 0],
      }),
      body({
        id: 'blue-star',
        name: 'Blue star',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.16,
        renderRadius: 0.16,
        color: '#82b8ff',
        position: [1, 0, 0],
        velocity: [0, 0.5, 0],
      }),
    ],
  },
  {
    id: 'figure-eight',
    name: 'Figure eight',
    summary: 'Three identical bodies trace a stable choreographic orbit.',
    fixedStep: 0.0015,
    timeScale: 0.55,
    cameraDistance: 4.8,
    trailSpan: 10,
    bodies: [
      body({
        id: 'body-a',
        name: 'Body A',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.1,
        renderRadius: 0.1,
        color: '#ff8f70',
        position: [-0.97000436, 0.24308753, 0],
        velocity: [0.466203685, 0.43236573, 0],
      }),
      body({
        id: 'body-b',
        name: 'Body B',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.1,
        renderRadius: 0.1,
        color: '#79d9ff',
        position: [0.97000436, -0.24308753, 0],
        velocity: [0.466203685, 0.43236573, 0],
      }),
      body({
        id: 'body-c',
        name: 'Body C',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.1,
        renderRadius: 0.1,
        color: '#bc96ff',
        position: [0, 0, 0],
        velocity: [-0.93240737, -0.86473146, 0],
      }),
    ],
  },
  {
    id: 'head-on-collision',
    name: 'Head-on collision',
    summary: 'Two equal bodies fall together and merge in a perfectly inelastic collision.',
    fixedStep: 0.0015,
    timeScale: 0.6,
    cameraDistance: 4.2,
    trailSpan: 8,
    bodies: [
      body({
        id: 'collision-left',
        name: 'Left body',
        kind: 'terrestrial',
        surface: 'earth',
        mass: 1,
        radius: 0.18,
        renderRadius: 0.18,
        color: '#ff9b63',
        position: [-0.8, 0, 0],
        velocity: [0.12, 0, 0],
      }),
      body({
        id: 'collision-right',
        name: 'Right body',
        kind: 'rocky',
        surface: 'mars',
        mass: 1,
        radius: 0.18,
        renderRadius: 0.18,
        color: '#70cfff',
        position: [0.8, 0, 0],
        velocity: [-0.12, 0, 0],
      }),
    ],
  },
] as const satisfies readonly SimulationPreset[];

export type PresetId = (typeof presets)[number]['id'];

export const getPreset = (id: string): SimulationPreset =>
  presets.find((preset) => preset.id === id) ?? presets[0];
