import type { BodyDefinition } from './types';

export interface SimulationPreset {
  readonly id: string;
  readonly name: string;
  readonly summary: string;
  readonly bodies: readonly BodyDefinition[];
  readonly fixedStep: number;
  /** Physical seconds represented by one integration-time unit. */
  readonly secondsPerTimeUnit: number;
  /** Physical seconds advanced for each real second at startup. */
  readonly defaultTimeWarp: number;
  readonly cameraDistance: number;
  readonly trailSpan: number;
}

const body = (definition: BodyDefinition): BodyDefinition => definition;

// sqrt(AU^3 / GM_sun): the natural time unit when G = M_sun = AU = 1.
export const AU_SOLAR_MASS_TIME_UNIT_SECONDS = 5_022_642.891_366_037;

const rotationRateForPeriod = (periodSeconds: number): number =>
  (Math.PI * 2 * AU_SOLAR_MASS_TIME_UNIT_SECONDS) / periodSeconds;

const barycentricBodies = (definitions: readonly BodyDefinition[]): BodyDefinition[] => {
  const totalMass = definitions.reduce((sum, definition) => sum + definition.mass, 0);
  const center = [0, 0, 0];
  const centerVelocity = [0, 0, 0];

  for (const definition of definitions) {
    for (let component = 0; component < 3; component += 1) {
      center[component] =
        center[component]! + definition.position[component]! * definition.mass;
      centerVelocity[component] =
        centerVelocity[component]! + definition.velocity[component]! * definition.mass;
    }
  }

  return definitions.map((definition) => ({
    ...definition,
    position: [
      definition.position[0] - center[0]! / totalMass,
      definition.position[1] - center[1]! / totalMass,
      definition.position[2] - center[2]! / totalMass,
    ],
    velocity: [
      definition.velocity[0] - centerVelocity[0]! / totalMass,
      definition.velocity[1] - centerVelocity[1]! / totalMass,
      definition.velocity[2] - centerVelocity[2]! / totalMass,
    ],
  }));
};

export const presets = [
  {
    id: 'solar-system',
    name: 'Idealized solar system',
    summary: 'JPL-derived mass ratios and orbital scales in a circular, coplanar model.',
    fixedStep: 0.0025,
    secondsPerTimeUnit: AU_SOLAR_MASS_TIME_UNIT_SECONDS,
    defaultTimeWarp: 1_000_000,
    cameraDistance: 42,
    trailSpan: 72,
    bodies: [
      body({
        id: 'sun',
        name: 'Sun',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.00465047,
        renderRadius: 0.34,
        color: '#ffd685',
        axialTilt: 0.1265,
        rotationRate: 14.18,
        position: [-0.010085310860747045, 0, 0],
        velocity: [0, -0.000536927021530575, 0],
      }),
      body({
        id: 'mercury',
        name: 'Mercury',
        kind: 'rocky',
        surface: 'mercury',
        mass: 1.66012082546e-7,
        radius: 0.000016306,
        renderRadius: 0.052,
        color: '#b9aca0',
        axialTilt: 0.00059,
        rotationRate: 6.228,
        position: [0.38709927, 0, 0],
        velocity: [0, 1.6072699454, 0],
      }),
      body({
        id: 'venus',
        name: 'Venus',
        kind: 'terrestrial',
        surface: 'venus',
        mass: 2.4478382878e-6,
        radius: 0.000040454,
        renderRadius: 0.071,
        color: '#e7b675',
        axialTilt: 3.095,
        rotationRate: -1.503,
        position: [0.72333566, 0, 0],
        velocity: [0, 1.17579081149, 0],
      }),
      body({
        id: 'earth',
        name: 'Earth',
        kind: 'terrestrial',
        surface: 'earth',
        mass: 3.00348961546e-6,
        radius: 0.000042587,
        renderRadius: 0.078,
        color: '#6ca9ff',
        axialTilt: 0.4091,
        rotationRate: 366.24,
        position: [1.00000261, 0, 0],
        velocity: [0, 0.999998695003, 0],
      }),
      body({
        id: 'mars',
        name: 'Mars',
        kind: 'rocky',
        surface: 'mars',
        mass: 3.22715608293e-7,
        radius: 0.000022657,
        renderRadius: 0.061,
        color: '#df7557',
        axialTilt: 0.4396,
        rotationRate: 356.0,
        position: [1.52371034, 0, 0],
        velocity: [0, 0.810118952798, 0],
      }),
      body({
        id: 'jupiter',
        name: 'Jupiter',
        kind: 'gas-giant',
        surface: 'jupiter',
        mass: 9.54791909941e-4,
        radius: 0.00046733,
        renderRadius: 0.18,
        color: '#deb488',
        axialTilt: 0.0546,
        rotationRate: 883.2,
        position: [5.202887, 0, 0],
        velocity: [0, 0.438407326353, 0],
      }),
      body({
        id: 'saturn',
        name: 'Saturn',
        kind: 'gas-giant',
        surface: 'saturn',
        mass: 2.85885670025e-4,
        radius: 0.00038926,
        renderRadius: 0.16,
        color: '#e8d09b',
        axialTilt: 0.4665,
        rotationRate: 822.6,
        position: [9.53667594, 0, 0],
        velocity: [0, 0.323818373694, 0],
      }),
      body({
        id: 'uranus',
        name: 'Uranus',
        kind: 'ice-giant',
        surface: 'uranus',
        mass: 4.365e-5,
        radius: 0.00016953,
        renderRadius: 0.12,
        color: '#a8e2e8',
        axialTilt: 1.706,
        rotationRate: -508.7,
        position: [19.18916464, 0, 0],
        velocity: [0, 0.228282843203, 0],
      }),
      body({
        id: 'neptune',
        name: 'Neptune',
        kind: 'ice-giant',
        surface: 'neptune',
        mass: 5.149e-5,
        radius: 0.00016459,
        renderRadius: 0.12,
        color: '#477ceb',
        axialTilt: 0.4943,
        rotationRate: 543.9,
        position: [30.06992276, 0, 0],
        velocity: [0, 0.182361783677, 0],
      }),
    ],
  },
  {
    id: 'black-hole-flyby',
    name: 'Black hole flyby',
    summary: 'A compact object crosses a young planetary system and exchanges energy with every body.',
    fixedStep: 0.001,
    secondsPerTimeUnit: AU_SOLAR_MASS_TIME_UNIT_SECONDS,
    defaultTimeWarp: 1_000_000,
    cameraDistance: 8.5,
    trailSpan: 16,
    bodies: barycentricBodies([
      body({
        id: 'flyby-star',
        name: 'Host star',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.075,
        renderRadius: 0.22,
        color: '#ffd284',
        axialTilt: 0.12,
        rotationRate: 2.4,
        position: [0, 0, 0],
        velocity: [0, 0, 0],
      }),
      body({
        id: 'inner-world',
        name: 'Inner world',
        kind: 'terrestrial',
        surface: 'earth',
        mass: 0.002,
        radius: 0.025,
        renderRadius: 0.082,
        color: '#68a8ee',
        axialTilt: 0.31,
        rotationRate: 4.2,
        position: [0.9, 0, 0],
        velocity: [0, 1.054, 0],
      }),
      body({
        id: 'outer-giant',
        name: 'Outer giant',
        kind: 'gas-giant',
        surface: 'jupiter',
        mass: 0.015,
        radius: 0.055,
        renderRadius: 0.14,
        color: '#d9af82',
        axialTilt: 0.08,
        rotationRate: 5.8,
        position: [1.8, 0, 0],
        velocity: [0, 0.745, 0],
      }),
      body({
        id: 'intruder-black-hole',
        name: 'Intruder black hole',
        kind: 'black-hole',
        surface: 'accretion-disk',
        mass: 2,
        radius: 0.04,
        renderRadius: 0.17,
        color: '#ff9d52',
        axialTilt: -0.34,
        rotationRate: 1.2,
        position: [-5.2, -1.25, 0],
        velocity: [0.74, 0.11, 0],
      }),
    ]),
  },
  {
    id: 'black-hole-binary',
    name: 'Black hole and star',
    summary: 'A star and a black hole orbit their barycentre while two worlds respond to the combined field.',
    fixedStep: 0.001,
    secondsPerTimeUnit: AU_SOLAR_MASS_TIME_UNIT_SECONDS,
    defaultTimeWarp: 1_000_000,
    cameraDistance: 10,
    trailSpan: 20,
    bodies: barycentricBodies([
      body({
        id: 'binary-black-hole',
        name: 'Black hole',
        kind: 'black-hole',
        surface: 'accretion-disk',
        mass: 4,
        radius: 0.08,
        renderRadius: 0.19,
        color: '#ffac67',
        axialTilt: -0.32,
        rotationRate: 1.4,
        position: [-0.5, 0, 0],
        velocity: [0, -0.2828427125, 0],
      }),
      body({
        id: 'binary-star-companion',
        name: 'Companion star',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.085,
        renderRadius: 0.23,
        color: '#a8caff',
        axialTilt: 0.08,
        rotationRate: 2.1,
        position: [2, 0, 0],
        velocity: [0, 1.13137085, 0],
      }),
      body({
        id: 'circumbinary-world',
        name: 'Circumbinary world',
        kind: 'terrestrial',
        surface: 'earth',
        mass: 0.001,
        radius: 0.022,
        renderRadius: 0.085,
        color: '#5ea4f0',
        axialTilt: 0.42,
        rotationRate: 4.6,
        position: [0, 5.2, 0],
        velocity: [-0.981, 0, 0],
      }),
      body({
        id: 'outer-ice-world',
        name: 'Outer ice world',
        kind: 'ice-giant',
        surface: 'neptune',
        mass: 0.004,
        radius: 0.038,
        renderRadius: 0.11,
        color: '#477ceb',
        axialTilt: 0.5,
        rotationRate: 3.8,
        position: [0, -7.2, 0],
        velocity: [0.834, 0, 0],
      }),
    ]),
  },
  {
    id: 'black-hole-merger',
    name: 'Black hole merger',
    summary: 'Two horizons fall together; the remnant retains momentum while an estimated mass fraction leaves as gravitational radiation.',
    fixedStep: 0.0005,
    secondsPerTimeUnit: AU_SOLAR_MASS_TIME_UNIT_SECONDS,
    defaultTimeWarp: 1_000_000,
    cameraDistance: 4.6,
    trailSpan: 8,
    bodies: barycentricBodies([
      body({
        id: 'merger-primary',
        name: 'Primary black hole',
        kind: 'black-hole',
        surface: 'none',
        mass: 3,
        radius: 0.06,
        renderRadius: 0.21,
        color: '#ffb05f',
        axialTilt: -0.28,
        rotationRate: 1.1,
        position: [-0.6, 0, 0],
        velocity: [0.18, 0, 0],
      }),
      body({
        id: 'merger-secondary',
        name: 'Secondary black hole',
        kind: 'black-hole',
        surface: 'none',
        mass: 2,
        radius: 0.04,
        renderRadius: 0.17,
        color: '#77aaff',
        axialTilt: -0.21,
        rotationRate: -1.3,
        position: [0.9, 0, 0],
        velocity: [-0.27, 0, 0],
      }),
    ]),
  },
  {
    id: 'tidal-encounter',
    name: 'Tidal stellar encounter',
    summary: 'A star passes close enough to a black hole for the tidal gradient to overcome stellar surface gravity.',
    fixedStep: 0.00035,
    secondsPerTimeUnit: AU_SOLAR_MASS_TIME_UNIT_SECONDS,
    defaultTimeWarp: 250_000,
    cameraDistance: 4.2,
    trailSpan: 6,
    bodies: barycentricBodies([
      body({
        id: 'tidal-black-hole',
        name: 'Tidal black hole',
        kind: 'black-hole',
        surface: 'accretion-disk',
        mass: 6,
        radius: 0.12,
        renderRadius: 0.23,
        color: '#ffb36b',
        axialTilt: -0.35,
        rotationRate: 1.4,
        position: [0, 0, 0],
        velocity: [0, 0, 0],
      }),
      body({
        id: 'tidally-stretched-star',
        name: 'Tidally stretched star',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.12,
        renderRadius: 0.17,
        color: '#ffe0a1',
        axialTilt: 0.14,
        rotationRate: 6.2,
        position: [-0.85, 0, 0],
        velocity: [1.35, -0.3, 0],
      }),
    ]),
  },
  {
    id: 'horizon-capture',
    name: 'Horizon capture',
    summary: 'A rocky body falls through a black hole capture radius after visible tidal stretching.',
    fixedStep: 0.0003,
    secondsPerTimeUnit: AU_SOLAR_MASS_TIME_UNIT_SECONDS,
    defaultTimeWarp: 250_000,
    cameraDistance: 3.8,
    trailSpan: 5,
    bodies: barycentricBodies([
      body({
        id: 'capture-black-hole',
        name: 'Capturing black hole',
        kind: 'black-hole',
        surface: 'accretion-disk',
        mass: 4,
        radius: 0.08,
        renderRadius: 0.21,
        color: '#ffad68',
        axialTilt: -0.27,
        rotationRate: 1.2,
        position: [0.12, 0, 0],
        velocity: [0, 0, 0],
      }),
      body({
        id: 'captured-world',
        name: 'Captured rocky world',
        kind: 'rocky',
        surface: 'mars',
        mass: 0.025,
        radius: 0.04,
        renderRadius: 0.11,
        color: '#d97954',
        axialTilt: 0.31,
        rotationRate: 5.4,
        position: [-0.56, 0.035, 0],
        velocity: [1.1, -0.06, 0],
      }),
    ]),
  },
  {
    id: 'binary-stars',
    name: 'Binary stars',
    summary: 'Two equal stars orbit their shared center of mass.',
    fixedStep: 0.0025,
    secondsPerTimeUnit: AU_SOLAR_MASS_TIME_UNIT_SECONDS,
    defaultTimeWarp: 1_000_000,
    cameraDistance: 5.5,
    trailSpan: 12,
    bodies: [
      body({
        id: 'amber-star',
        name: 'Amber star',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.16,
        renderRadius: 0.16,
        color: '#ffc66d',
        position: [-1, 0, 0],
        velocity: [0, -0.5, 0],
      }),
      body({
        id: 'blue-star',
        name: 'Blue star',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.16,
        renderRadius: 0.16,
        color: '#82b8ff',
        position: [1, 0, 0],
        velocity: [0, 0.5, 0],
      }),
    ],
  },
  {
    id: 'stellar-merger',
    name: 'Stellar merger',
    summary: 'Two ordinary stars make an off-axis low-speed contact and form an expanded luminous remnant.',
    fixedStep: 0.0004,
    secondsPerTimeUnit: AU_SOLAR_MASS_TIME_UNIT_SECONDS,
    defaultTimeWarp: 1_000_000,
    cameraDistance: 4.2,
    trailSpan: 6,
    bodies: barycentricBodies([
      body({
        id: 'stellar-merger-primary',
        name: 'Primary star',
        kind: 'star',
        surface: 'sun',
        mass: 1.4,
        radius: 0.18,
        renderRadius: 0.22,
        color: '#ffd38a',
        axialTilt: 0.18,
        rotationRate: 2.3,
        position: [-0.36, -0.055, 0],
        velocity: [0.32, 0, 0],
      }),
      body({
        id: 'stellar-merger-secondary',
        name: 'Companion star',
        kind: 'star',
        surface: 'sun',
        mass: 0.8,
        radius: 0.14,
        renderRadius: 0.18,
        color: '#ff9d65',
        axialTilt: -0.12,
        rotationRate: -3.1,
        position: [0.36, 0.055, 0],
        velocity: [-0.42, 0, 0],
      }),
    ]),
  },
  {
    id: 'figure-eight',
    name: 'Figure eight',
    summary: 'Three identical bodies trace a stable choreographic orbit.',
    fixedStep: 0.0015,
    secondsPerTimeUnit: AU_SOLAR_MASS_TIME_UNIT_SECONDS,
    defaultTimeWarp: 1_000_000,
    cameraDistance: 4.8,
    trailSpan: 10,
    bodies: [
      body({
        id: 'body-a',
        name: 'Body A',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.1,
        renderRadius: 0.1,
        color: '#ff8f70',
        position: [-0.97000436, 0.24308753, 0],
        velocity: [0.466203685, 0.43236573, 0],
      }),
      body({
        id: 'body-b',
        name: 'Body B',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.1,
        renderRadius: 0.1,
        color: '#79d9ff',
        position: [0.97000436, -0.24308753, 0],
        velocity: [0.466203685, 0.43236573, 0],
      }),
      body({
        id: 'body-c',
        name: 'Body C',
        kind: 'star',
        surface: 'sun',
        mass: 1,
        radius: 0.1,
        renderRadius: 0.1,
        color: '#bc96ff',
        position: [0, 0, 0],
        velocity: [-0.93240737, -0.86473146, 0],
      }),
    ],
  },
  {
    id: 'head-on-collision',
    name: 'Planetary accretion',
    summary: 'Two equal worlds meet below the catastrophic threshold and form one volume-equivalent remnant.',
    fixedStep: 0.0015,
    secondsPerTimeUnit: AU_SOLAR_MASS_TIME_UNIT_SECONDS,
    defaultTimeWarp: 1_000_000,
    cameraDistance: 4.2,
    trailSpan: 8,
    bodies: [
      body({
        id: 'collision-left',
        name: 'Left body',
        kind: 'terrestrial',
        surface: 'earth',
        mass: 1,
        radius: 0.18,
        renderRadius: 0.18,
        color: '#ff9b63',
        position: [-0.8, -0.075, 0],
        velocity: [0.12, 0, 0],
      }),
      body({
        id: 'collision-right',
        name: 'Right body',
        kind: 'rocky',
        surface: 'mars',
        mass: 1,
        radius: 0.18,
        renderRadius: 0.18,
        color: '#70cfff',
        position: [0.8, 0.075, 0],
        velocity: [-0.12, 0, 0],
      }),
    ],
  },
  {
    id: 'accreting-black-hole',
    name: 'Accreting black hole',
    summary: 'A stellar-mass Schwarzschild black hole, a thin luminous disk, and two gravitating companions share one scene.',
    fixedStep: 0.00075,
    secondsPerTimeUnit: AU_SOLAR_MASS_TIME_UNIT_SECONDS,
    defaultTimeWarp: 1_000_000,
    cameraDistance: 10,
    trailSpan: 18,
    bodies: barycentricBodies([
      body({
        id: 'accreting-primary',
        name: 'Accreting black hole',
        kind: 'black-hole',
        surface: 'accretion-disk',
        mass: 5,
        radius: 0.1,
        renderRadius: 0.2,
        color: '#ffd6a0',
        axialTilt: -0.72,
        rotationRate: 0,
        position: [0, 0, 0],
        velocity: [0, 0, 0],
      }),
      body({
        id: 'accreting-companion',
        name: 'Companion star',
        kind: 'star',
        surface: 'sun',
        mass: 0.04,
        radius: 0.045,
        renderRadius: 0.15,
        color: '#c7deff',
        axialTilt: 0.18,
        rotationRate: 5.2,
        position: [3.2, 0, 0],
        velocity: [0, 1.25, 0],
      }),
      body({
        id: 'accreting-outer-world',
        name: 'Outer world',
        kind: 'gas-giant',
        surface: 'jupiter',
        mass: 0.002,
        radius: 0.022,
        renderRadius: 0.09,
        color: '#d1a376',
        axialTilt: 0.08,
        rotationRate: 17,
        position: [-5.5, 0, 0],
        velocity: [0, -0.953, 0],
      }),
    ]),
  },
  {
    id: 'quasar-system',
    name: 'Active galactic nucleus',
    summary: 'A radio-loud quasar engine and nearby bodies share one live gravitational scene; disk and jets are emission overlays, not extra forces.',
    fixedStep: 0.00075,
    secondsPerTimeUnit: AU_SOLAR_MASS_TIME_UNIT_SECONDS,
    defaultTimeWarp: 1_000_000,
    cameraDistance: 11,
    trailSpan: 18,
    bodies: barycentricBodies([
      body({
        id: 'active-nucleus',
        name: 'Active nucleus',
        kind: 'black-hole',
        surface: 'quasar',
        mass: 8,
        radius: 0.16,
        renderRadius: 0.22,
        color: '#fff0c2',
        axialTilt: -0.3,
        rotationRate: 0,
        position: [0, 0, 0],
        velocity: [0, 0, 0],
      }),
      body({
        id: 'nuclear-star',
        name: 'Nuclear star',
        kind: 'star',
        surface: 'sun',
        mass: 0.02,
        radius: 0.035,
        renderRadius: 0.13,
        color: '#b8d8ff',
        axialTilt: 0.12,
        rotationRate: 8,
        position: [3, 0, 0],
        velocity: [0, 1.633, 0],
      }),
      body({
        id: 'outer-giant-quasar',
        name: 'Outer giant',
        kind: 'gas-giant',
        surface: 'jupiter',
        mass: 0.006,
        radius: 0.025,
        renderRadius: 0.1,
        color: '#d3a77f',
        axialTilt: 0.08,
        rotationRate: 22,
        position: [-5, 0, 0],
        velocity: [0, -1.265, 0],
      }),
    ]),
  },
  {
    id: 'pulsar-system',
    name: 'Pulsar system',
    summary: 'A 1.337-second rotating neutron star sweeps idealized magnetic-axis beams while all companions respond to its mass.',
    fixedStep: 0.001,
    secondsPerTimeUnit: AU_SOLAR_MASS_TIME_UNIT_SECONDS,
    defaultTimeWarp: 1,
    cameraDistance: 5.6,
    trailSpan: 11,
    bodies: barycentricBodies([
      body({
        id: 'pulsar-primary',
        name: 'Pulsar',
        kind: 'pulsar',
        surface: 'pulsar',
        mass: 1.4,
        radius: 2e-7,
        renderRadius: 0.105,
        color: '#c8f4ff',
        axialTilt: 0.17,
        rotationRate: rotationRateForPeriod(1.337),
        position: [0, 0, 0],
        velocity: [0, 0, 0],
      }),
      body({
        id: 'pulsar-planet',
        name: 'Pulsar planet',
        kind: 'rocky',
        surface: 'procedural',
        mass: 1e-5,
        radius: 0.00003,
        renderRadius: 0.065,
        color: '#a98776',
        axialTilt: 0.34,
        rotationRate: 120,
        position: [1, 0, 0],
        velocity: [0, 1.18322, 0],
      }),
      body({
        id: 'pulsar-companion',
        name: 'Distant companion',
        kind: 'rocky',
        surface: 'procedural',
        mass: 0.05,
        radius: 0.012,
        renderRadius: 0.09,
        color: '#c99472',
        axialTilt: 0.09,
        rotationRate: 38,
        position: [-2.5, 0, 0],
        velocity: [0, -0.74833, 0],
      }),
    ]),
  },
  {
    id: 'neutron-star-binary',
    name: 'Double neutron stars',
    summary: 'Two compact massive stars orbit a barycentre; the dynamics remain Newtonian and do not claim relativistic inspiral radiation.',
    fixedStep: 0.0005,
    secondsPerTimeUnit: AU_SOLAR_MASS_TIME_UNIT_SECONDS,
    defaultTimeWarp: 1_000_000,
    cameraDistance: 4.8,
    trailSpan: 9,
    bodies: [
      body({
        id: 'neutron-star-a',
        name: 'Neutron star A',
        kind: 'neutron-star',
        surface: 'neutron-star',
        mass: 1.4,
        radius: 2e-7,
        renderRadius: 0.1,
        color: '#bfe9ff',
        axialTilt: 0.23,
        rotationRate: rotationRateForPeriod(0.47),
        position: [-0.8, 0, 0],
        velocity: [0, -0.661438, 0],
      }),
      body({
        id: 'neutron-star-b',
        name: 'Neutron star B',
        kind: 'neutron-star',
        surface: 'neutron-star',
        mass: 1.4,
        radius: 2e-7,
        renderRadius: 0.1,
        color: '#89bfff',
        axialTilt: -0.18,
        rotationRate: rotationRateForPeriod(2.77),
        position: [0.8, 0, 0],
        velocity: [0, 0.661438, 0],
      }),
    ],
  },
] as const satisfies readonly SimulationPreset[];

export type PresetId = (typeof presets)[number]['id'];

export const getPreset = (id: string): SimulationPreset =>
  presets.find((preset) => preset.id === id) ?? presets[0];
